name: sun
description: "sun - sinergi untuk negeri"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  async: ^2.11.0
  logger: ^2.0.2+1
  shared_preferences: ^2.0.10
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.1.3
  email_validator: ^2.1.17
  connectivity_plus: ^5.0.2
  url_launcher: ^6.0.6
  intl: ^0.19.0
  webview_flutter: ^2.0.13
  # webview_flutter: ^4.7.0
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  decimal: ^2.3.3
  flutter_cache_manager: ^3.1.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  timeago: ^3.6.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/codedevsulut_logo.png
    - assets/images/sun.png
    - assets/images/illustration-environment.png
    - assets/images/emoji-solar-energy.png
    - assets/images/icon-charity-9wV.png
    - assets/images/icon-insurance-disaster.png
    - assets/images/whatsapp-image-2023-07-24-at-323-1-TE7.png
    - assets/images/rectangle-17.png
    - assets/images/snapinsta-1.png
    - assets/images/snapinsta-5.png
    - assets/images/launcher.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/launcher.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"